global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: /metrics
remote_write:
  - url: http://host.docker.internal:9090/api/v1/write
    basic_auth:
      username: admin
      password: admin
