export const MACHINE_DASHBOARD_MAP = {
  "Cathode Mixing": "cathode-mixing-uid",
  "Cathode Coating": "cathode-coating-uid",
  "Cathode Drying": "cathode-drying-uid",
  "Cathode Calendaring": "cathode-calendaring-uid",
  "Cathode Inspection": "cathode-inspection-uid",
  "Cathode Slitting": "cathode-slitting-uid",
  "Anode Mixing": "anode-mixing-uid",
  "Anode Coating": "anode-coating-uid",
  "Anode Drying": "anode-drying-uid",
  "Anode Calendaring": "anode-calendaring-uid",
  "Anode Slitting": "anode-slitting-uid",
  "Anode Inspection": "anode-inspection-uid",
  Rewinding: "rewinding-uid",
  "Electrolyte Filling": "electrolyte-filling-uid",
  "Formation Cycling": "formation-cycling-uid",
  Aging: "aging-uid",
};
